# Changes here will be overwritten by Copier
_commit: 2.6.0-32-g80178a8
_src_path: ../python-copier-template
author_email: daniel.fernandes@diamond.ac.uk
author_name: Daniel Fernandes
description: Testing new feature in python-copier-template
distribution_name: dan-fernandes-test-python-copier-template
docker: true
docs_type: sphinx
git_platform: github.com
github_org: dan-fernandes
package_name: dan_fernandes_test_python_copier_template
pypi: true
repo_name: dan-fernandes-test-python-copier-template
strict_typing: false
type_checker: pyright
